name: ariadne_gpu
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.9.*
  - numpy
  - matplotlib
  - pyyaml
  - pandas
  - seaborn
  - ipywidgets
  - h5py<3.2
  - scikit-learn
  - nose
  - notebook
  - torchvision
  - cudatoolkit
  - pytorch
  - pytorch-lightning
  - torchmetrics
  - gin-config
  - absl-py
  - faiss