name: ariadne_cpu
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.8.*
  - numpy
  - matplotlib
  - pyyaml
  - pandas
  - scikit-learn
  - nose=1.3.7
  - pytables
  - memory_profiler
  - notebook
  - torchvision
  - cpuonly=1.0
  - pytorch
  - pyqt=5.12.*
  - vispy=0.6.4
  - pytorch-lightning
  - gin-config
  - absl-py
  - faiss
