name: ariadne_gpu
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.8.*
  - numpy
  - matplotlib
  - pyyaml
  - pandas
  - scikit-learn
  - nose=1.3.7
  - notebook
  - torchvision
  - cudatoolkit=10.1
  - pytorch
  - pyqt=5.12.*
  - vispy=0.6.6
  - pytorch-lightning
  - torchmetrics
  - gin-config
  - absl-py
  - faiss