name: conda_cpu_env
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py38h1e8a9f7_1
  - attrs=20.1.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.1=py38hba49e27_0
  - colorama=0.4.3=py_0
  - cpuonly=1.0=0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38h32f6830_1001
  - freetype=2.10.2=hd328e21_0
  - freetype-py=2.2.0=pyh9f0ad1d_0
  - icu=67.1=h33f27b4_0
  - importlib-metadata=1.7.0=py38h32f6830_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.17.0=py38h1cdfbd6_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.2=py38_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=he774522_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - kiwisolver=1.2.0=py38heaebd3c_0
  - libclang=10.0.1=default_hf44288c_1
  - libpng=1.6.37=ha81a0f5_2
  - libsodium=1.0.17=h2fa13f4_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38h9de7a3e_1
  - matplotlib=3.3.1=1
  - matplotlib-base=3.3.1=py38hfb9ee82_1
  - mistune=0.8.4=py38h9de7a3e_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.1.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.7=py_0
  - ninja=1.10.0=py38h7ef1ec2_0
  - notebook=6.1.3=py38h32f6830_0
  - numpy=1.19.1=py38h5510c5b_0
  - numpy-base=1.19.1=py38ha3acd2a_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=he774522_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.1=py38ha925a31_0
  - pandoc=2.10.1=he774522_0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.2=py_0
  - pickleshare=0.7.5=py38h32f6830_1001
  - pillow=7.2.0=py38hcc1f983_0
  - pip=20.2.2=py38_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.6=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h6538335_1
  - pyrsistent=0.16.0=py38h9de7a3e_0
  - python=3.8.5=he1778fa_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.6.0=py3.8_cpu_0
  - pytz=2020.1=py_0
  - pywin32=227=py38hfa6e2cd_0
  - pywinpty=0.5.7=py38_0
  - pyyaml=5.3.1=py38he774522_1
  - pyzmq=19.0.2=py38h77b9d75_0
  - qt=5.12.6=hb2cf2c5_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=he774522_0
  - torchvision=0.7.0=py38_cpu
  - tornado=6.0.4=py38hfa6e2cd_0
  - traitlets=4.3.3=py38h32f6830_1
  - vc=14.1=h0510ff6_4
  - vispy=0.6.4=py38h4b8e87e_1
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.2=ha925a31_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: C:\Miniconda3\envs\conda_cpu_env

